### PR TITLE
Add signature support for HoverHandler.

### PR DESCRIPTION
**Pull request by yaohaizh**

### CODE REVIEW

**Comment by aeschli** [comment]
Cool, thanks @yaohaizh! I just compared with the [Javadoc hover](https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/hover/JavadocHover.java) in Eclipse and think we should also fully qualify the mains element name, for extra information:

image

**Comment by aeschli** [comment]
I think it's fine to make the pull request against https://github.com/eclipse/eclipse.jdt.ls, it's good.

**Comment by akaroml** [comment]
While trying to understand the problem, can we link this pull request to an issue to help recover the context quicker?

**Comment by aeschli** [comment]
Yes, we can create an issue as well. I created https://github.com/eclipse/eclipse.jdt.ls/issues/259

**Pull request closed without merging**
